accounts/urls.py
from django.urls import path
from accounts import views

#TEMPLATE URLS
app_name = 'accounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('home/',views.home, name='home'),
    path('user_login/',views.user_login, name='user_login'),
    path('logout/',views.user_logout,name='logout'),
    path('about/',views.about, name='about'),
    path('accounts/',views.account_page_view, name='account_page'),
    path('accounts/product_add/',views.add_quantity,name='product_add'),
    path('accounts/product_subtract/',views.subtract_quantity,name='product_subtract'),
    path('accounts/purchase/',views.purchase_page_view, name='purchase_page')
]

app1/urls.py
from django.urls import path
from app1 import views

urlpatterns = [
    path('',views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('home/',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('about/',views.about, name='about')
]

eCom/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views as account_views
from merchant import views as merchant_views
from products import urls as produrls
from merchant import urls as mercurls
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mdb/',views.mdb_home_page_view,name="mdb_home_page"),
    path('',include('accounts.urls',namespace='accounts')),
    path('logout/',account_views.user_logout,name='user_logout'),
    path('products/',include(produrls,namespace='products')),
    path('merchant/',include(mercurls,namespace='merchant')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchant/urls.py
from django.urls import path
from merchant import views 
from accounts import views as account_views

#TEMPLATE URLS
app_name = 'merchant'

urlpatterns = [
    path('',views.merchant_login, name='merchant_login'),
    path('register',views.register_product, name='register_product'),
    path('merchant_login/',views.merchant_login, name='merchant_login'),
    path('logout/',views.merchant_logout,name='logout')
    # path('about/',account_views.about, name='about'),
]

products/urls.py
from django.urls import path
from products import views

#TEMPLATE URLS
app_name = 'products'

urlpatterns = [
    path('list/',views.product_list_view,name='prodlist'),
    path('list/<product_id>/',views.product_detail_view,name='proddetail'),
]

accounts/models.py
from django.db import models
from products.models import Phone
from django.urls import reverse

class User(models.Model):
    username = models.CharField(max_length=200, unique=True)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=254, unique=True)
    delivery_address = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=10, unique=True)
    password = models.CharField(max_length=200)

    def __str__(self):
        return self.username

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return "Cart of %s" % self.user.username

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart,on_delete=models.CASCADE,related_name='cart_containing_product')
    product = models.ForeignKey(Phone,on_delete=models.CASCADE,related_name='product_in_cart')
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return "Item in cart: %s " % self.product.name

class Purchase(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return "Purchase of %s" % self.user.username

class PurchaseProduct(models.Model):
    purchase = models.ForeignKey(Purchase,on_delete=models.CASCADE,related_name='purchase_containing_product')
    product = models.ForeignKey(Phone,on_delete=models.CASCADE,related_name='product_in_purchase')
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return "Item in purchase: %s " % self.product.name

accounts/forms.py
from django import forms
from accounts.models import User


def username_validator(value):
    if not(value.isalnum()):
        raise forms.ValidationError("Username is not valid. Must contain only alphanumeric characters.")
    if len(value)<4:
        raise forms.ValidationError("Username is not valid. Must contain atleast 4 characters.")

def phonenum_validator(value):
    if len(value)!=10:
        raise forms.ValidationError("Phone number is not valid. Must contain exactly 10 digits.")

def address_validator(value):
    if len(value)<20:
        raise forms.ValidationError("Please enter a valid delivery_address.")

def flname_validator(value):
    if not(value.isalpha()):
        raise forms.ValidationError("Should only contain alphabets. Are you Elon Musk's son? If you are, you are too young. Bye bye!")


class SignupForm(forms.ModelForm):
    # Form fields
    username = forms.CharField(validators=[username_validator], widget=forms.TextInput(attrs={'name':'username', 'type':'text', 'id':'user_username', 'class':'form-control', 'required':True, 'placeholder':"Enter Username"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'name':'user_password', 'type':'password', 'id':'InputPassword', 'class':'form-control', 'required':True}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'name':'user_email', 'type':'email', 'id':'InputEmail', 'class':'form-control', 'required':True, 'placeholder':"Enter Email"}))
    first_name = forms.CharField(validators=[flname_validator], widget=forms.TextInput(attrs={'name':'first_name', 'type':'text', 'id':'user_first_name', 'class':'form-control', 'required':True, 'placeholder':"Enter First Name"}))
    last_name = forms.CharField(validators=[flname_validator], widget=forms.TextInput(attrs={'name':'last_name', 'type':'text', 'id':'user_last_name', 'class':'form-control', 'required':True, 'placeholder':"Enter Last Name"}))
    delivery_address = forms.CharField(validators=[address_validator], widget=forms.TextInput(attrs={'name':'delivery_address', 'type':'text', 'id':'user_address', 'class':'form-control', 'required':True, 'placeholder':"Enter Delivery Address"}))
    phone_number = forms.CharField(validators=[phonenum_validator], widget=forms.NumberInput(attrs={'name':'phone_number', 'type':'number', 'id':'user_phone_number', 'class':'form-control', 'required':True, 'placeholder':"Enter Phone Number"}))

    class Meta():
        model = User
        fields = "__all__"

accounts/views.py
from django.shortcuts import render
from accounts.models import User
from accounts.forms import SignupForm
from django.contrib.auth.hashers import make_password, check_password

from django.views.generic.detail import DetailView
from accounts.models import User, Cart, CartProduct, Purchase, PurchaseProduct
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

login_flag = False
curr_user = None
curr_user_object = None
# Create your views here.
def home(request):
    return render(request,'accounts/home.html', {'login_flag':login_flag})


def about(request):
    return render(request,'accounts/about.html', {'login_flag':login_flag})


def user_logout(request):
    global curr_user
    global login_flag

    login_flag = False
    curr_user = None

    return HttpResponseRedirect(reverse('accounts:home'))


def signup(request):
    global login_flag
    global curr_user

    user_form = SignupForm

    registered = False

    if request.method == 'POST':
        user_form = SignupForm(data=request.POST)

        if user_form.is_valid():
            curr_user_form = user_form.save()
            p_word = make_password(curr_user_form.password)
            curr_user_form.password = p_word
            curr_user_form.save()

            registered = True
            login_flag = True
            curr_user = curr_user_form.username

            cart_user = User.objects.get(username=curr_user)
            curr_cart = Cart(user=cart_user)
            curr_cart.save()

            purchase_user = User.objects.get(username=curr_user)
            curr_purchases = Purchase(user=purchase_user)
            curr_purchases.save()

  
            return HttpResponseRedirect(reverse('accounts:account_page'))

        else:
            print('user_form.errors')

    return render(request, 'accounts/signup.html', {'form':user_form, 'registered':registered})


def user_login(request):
    global login_flag
    global curr_user

    if request.method == 'POST':
        usrname = request.POST.get('username')
        passwrd = request.POST.get('password')

        if User.objects.filter(username=usrname).exists() and check_password(passwrd, User.objects.get(username=usrname).password):
            print("Logged in!")
            login_flag = True
            curr_user = usrname
            print("Current User is " + curr_user)

            return HttpResponseRedirect(reverse('accounts:account_page'))

        else:
            print("Someone tried to login and failed!")
            print("Type: {} Username: {} and password: {}".format(type(usrname),usrname,passwrd))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request, 'accounts/login.html',{'login_flag':login_flag})

def curr_user_find():
    current_user_object = User.objects.get(username=curr_user)
    return current_user_object

def account_page_view(request):
    global curr_user

    curruser = User.objects.get(username=curr_user)
    if Cart.objects.filter(user=curruser).exists():
        curr_cart = Cart.objects.get(user=curruser)
        curr_cart_product=[]
        curr_cart_product = CartProduct.objects.filter(cart=curr_cart)
        for product in curr_cart_product:
            print(product)

        total = 0
        num_products = 0
        for p in curr_cart_product:
            num_products += p.quantity
            total += p.quantity * p.product.price
        return render(request, 'accounts/account_page.html',{'cart':curr_cart, 'cart_products':curr_cart_product, 'login_flag':login_flag, 'total':total, 'num_products':num_products})

    else:
        return HttpResponse("Your cart is empty")

def purchase_page_view(request):
    # if request.GET.get("Purchase 'em all!") == "Purchase 'em all!" :
        global curr_user
        curruser = User.objects.get(username=curr_user)
        curr_cart = Cart.objects.get(user=curruser)
        curr_purchase = Purchase.objects.get(user=curruser)
        purchase_products = []
        purchase_products = CartProduct.objects.filter(cart=curr_cart)
        for curr_product in purchase_products:
            curr_purchase_product = PurchaseProduct(purchase=curr_purchase,product=curr_product.product,quantity=curr_product.quantity)
            curr_purchase_product.save()
            curr_cart_product = CartProduct.objects.get(cart=curr_cart,product=curr_product.product)
            curr_cart_product.delete()
        all_purchase_products = PurchaseProduct.objects.filter(purchase=curr_purchase)
        return render(request, 'accounts/account_purchase_page.html',{'purchase':curr_purchase, 'purchase_products':all_purchase_products, 'login_flag':login_flag})

def add_quantity(request):
    global curr_user

    curruser = User.objects.get(username=curr_user)
    curr_cart = Cart.objects.get(user=curruser)

    cart_product_id = request.GET.get('cart_product')
    cart_product = CartProduct.objects.get(id=cart_product_id)
    cart_product.quantity += 1
    cart_product.save()

    curr_cart_product = CartProduct.objects.filter(cart=curr_cart)

    return HttpResponseRedirect(reverse('accounts:account_page'))
    # return render(request, 'accounts/account_page.html',{'cart':curr_cart, 'cart_products':curr_cart_product, 'login_flag':login_flag})

def subtract_quantity(request):
    global curr_user

    curruser = User.objects.get(username=curr_user)
    curr_cart = Cart.objects.get(user=curruser)

    cart_product_id = request.GET.get('cart_product')
    cart_product = CartProduct.objects.get(id=cart_product_id)

    if cart_product.quantity == 1:
        CartProduct.objects.filter(id=cart_product_id).delete()
    else:
        cart_product.quantity -= 1
        cart_product.save()

    curr_cart_product = CartProduct.objects.filter(cart=curr_cart)

    return HttpResponseRedirect(reverse('accounts:account_page'))
    # return render(request, 'accounts/account_page.html',{'cart':curr_cart, 'cart_products':curr_cart_product, 'login_flag':login_flag, 'total':total})

templates/accounts/account_purchase_page.html
{% extends 'accounts/base.html' %}

{% block inherit %}
    <main class="mt-5 pt-4">
      <h2 class="my-5 h2 text-center">Previous Purchases</h2>
      <div class="row">
        <div class="col-md-4 mb-4">
        </div>
        <div class="col-md-4 mb-4">
          <ul class="list-group mb-3 z-depth-1">
            {% for purchase_product in purchase_products %}
              <li class="list-group-item d-flex justify-content-between lh-condensed">
                <div>
                  <h6 class="my-0">{{purchase_product.product.name}}</h6>
                  <small class="text-muted">{{purchase_product.quantity}}</small>
                </div>
                <span class="text-muted"> {{purchase_product.product.price}}</span>
              </li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </main>
{% endblock %}

templates/accounts/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>eCom</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    . @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="navbar-brand waves-effect" href="{% url 'accounts:home' %}" target="_blank">
              <strong class="blue-text">Home</strong>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:about' %}">About
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'merchant:merchant_login' %}">Merchant
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>

        <ul class="navbar-nav nav-flex-icons">
          {% if login_flag == True %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'products:prodlist' %}">
              <span class="clearfix d-none d-sm-inline-block"> Products </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:account_page' %}">
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:purchase_page' %}">
              <span class="clearfix d-none d-sm-inline-block"> Purchases </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'user_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:user_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block inherit %}

  {% endblock %}

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript">
    new WOW().init();
  </script>
</body>

</html>

templates/accounts/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Home eCom</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    . @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="navbar-brand waves-effect" href="{% url 'accounts:home' %}" target="_blank">
              <strong class="blue-text">Home</strong>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:about' %}">About
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'merchant:merchant_login' %}">Merchant
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>

        <ul class="navbar-nav nav-flex-icons">

          {% if login_flag == True %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'products:prodlist' %}">
              <span class="clearfix d-none d-sm-inline-block"> Products </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:account_page' %}">
             
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:purchase_page' %}">
              <span class="clearfix d-none d-sm-inline-block"> Purchases </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'user_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:user_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}

        </ul>

      </div>
    </div>
  </nav>

  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://www.newstatesman.com/sites/default/files/styles/cropped_article_image/public/blogs_2016/05/iphone_se_2_.jpg?itok=TkQb0SBM'); background-repeat: no-repeat; background-size: cover;">
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>iPhone SE</strong>
              </h1>
              <p>
                <strong>Arriving next Fall</strong>
              </p>
              <p class="mb-4 d-none d-md-block">
                <strong>Order now for limited edition</strong>
              </p>
              <a target="_blank" href="{% url 'accounts:user_login' %}" class="btn btn-outline-white btn-lg">Buy Now
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://images.unsplash.com/photo-1565967249821-083c4775e5bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1189&q=80'); background-repeat: no-repeat; background-size: cover;">
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Samsung Galaxy M51</strong>
              </h1>

              <p>
                <strong>20% off on all Samsung products</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong></strong>
              </p>

              <a target="_blank" href="{% url 'accounts:user_login' %}" class="btn btn-outline-white btn-lg">Buy Now
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="view" style="background-image: url('https://fdn2.gsmarena.com/vv/pics/google/google-pixel-4-xl-1.jpg'); background-repeat: no-repeat; background-size: cover;">
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <strong>Google Pixel 4 XL</strong>
              </h1>
              <p class="mb-4 d-none d-md-block">
                <strong></strong>
              </p>
              <a target="_blank" href="{% url 'accounts:user_login' %}" class="btn btn-outline-white btn-lg">Buy Now
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <!-- <div style="text-align:center" class="footer-copyright py-3">
  </div>
  <div style="text-align:center" class="footer-copyright py-3">
  </div>
  <div style="text-align:center" class="footer-copyright py-3">
  </div>
  <div style="text-align:center" class="footer-copyright py-3">
  </div>
  <div style="text-align:center" class="footer-copyright py-3">
  </div> -->
  <div class="row wow fadeIn">
    <div class="col-lg-4 col-md-12 mb-4">

      <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

    </div>
    <div class="col-lg-4 col-md-6 mb-4">

      <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

    </div>
    <div class="col-lg-4 col-md-6 mb-4">

      <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

    </div>
  </div>
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">
    <hr class="my-4">
    <div class="pb-4">
      <a href="#" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="#" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <div style="text-align:center" class="footer-copyright py-3">
      Made with ❤ by Dhanwin and Varun
    </div>
  </footer>
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript">
    new WOW().init();
  </script>
</body>

</html>

templates/accounts/login.html
<!DOCTYPE html>
{% extends "accounts/base.html" %}
{% load static %}

{% block inherit %}
<div style="text-align:center" class="footer-copyright py-3">
</div>
<div style="text-align:center" class="footer-copyright py-3">
</div>
<div style="text-align:center" class="footer-copyright py-3">
</div>

    {% if login_flag == False %}
    <div class="row">
      <div class="col-md-3 mb-2">
      </div>
      <div class="col-md-6 mb-2">
        <div class="card">
          {%csrf_token%}
          <form method="post" class='card-body' action="{% url 'accounts:user_login' %}">
              {% csrf_token %}
              <div class="form-group">
                  <label for="exampleInputUsername1">Username</label>
                  <input name="username" type="text" class="form-control" id="exampleInputUsername1" placeholder="Enter Username">
              </div>
              <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input name="password" type="password" class="form-control" id="exampleInputPassword1">
              </div>
              <button type="submit" class="btn btn-primary btn-lg btn-block ">Login</button>
          </form>
        </div>
      </div>
    </div>
    {% else %}
        <div class="container">
            <div class="jumbotron">
                <h1>You are already logged in! Go to Products to Buy</h1>
            </div>
        </div>
    {% endif %}

{% endblock %}