accounts/urls.py
from django.urls import path
from accounts import views

#TEMPLATE URLS
app_name = 'accounts'

urlpatterns = [
    path('',views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('home/',views.home, name='home'),
    path('user_login/',views.user_login, name='user_login'),
    path('logout/',views.user_logout,name='logout'),
    path('about/',views.about, name='about'),
    path('accounts/',views.account_page_view, name='account_page'),
    path('accounts/product_add/',views.add_quantity,name='product_add'),
    path('accounts/product_subtract/',views.subtract_quantity,name='product_subtract'),
    path('accounts/purchase/',views.purchase_page_view, name='purchase_page')
]

app1/urls.py
from django.urls import path
from app1 import views

urlpatterns = [
    path('',views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('home/',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('about/',views.about, name='about')
]

eCom/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views as account_views
from merchant import views as merchant_views
from products import urls as produrls
from merchant import urls as mercurls
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mdb/',views.mdb_home_page_view,name="mdb_home_page"),
    path('',include('accounts.urls',namespace='accounts')),
    path('logout/',account_views.user_logout,name='user_logout'),
    path('products/',include(produrls,namespace='products')),
    path('merchant/',include(mercurls,namespace='merchant')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from products import views

#TEMPLATE URLS
app_name = 'products'

urlpatterns = [
    path('list/',views.product_list_view,name='prodlist'),
    path('list/<product_id>/',views.product_detail_view,name='proddetail'),
]

products/models.py
from django.db import models

class Phone(models.Model):
    name = models.CharField(max_length=200, unique=True) #the phone model name
    color = models.CharField(max_length=50)
    display = models.CharField(max_length=50)
    storage = models.PositiveIntegerField()
    camera = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    processor = models.CharField(max_length=100)
    ram = models.PositiveIntegerField()
    picture = models.ImageField(upload_to='phone_pics', blank=True) #A phone may not need an associated picture; but blank can be set to false later
    price = models.PositiveIntegerField()
    
    def __str__(self):
        return self.name

products/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from accounts.views import curr_user_object
from accounts import views
from accounts.models import CartProduct, Cart
from . import models
# Create your views here.
phone=None

def product_list_view(request):
    curr_user_object = views.curr_user_find()
    all_products = models.Phone.objects.all()

    phone_matrix = []
    curr_list = []
    for smartphone in all_products:
        if len(curr_list) == 3:
            phone_matrix.append(curr_list)
            curr_list = []
        curr_list.append(smartphone)
    if curr_list:
        phone_matrix.append(curr_list)

    if request.GET.get('Add to cart!') == 'Add to cart!':
        curr_cart = Cart.objects.get(user=curr_user_object)
        if not CartProduct.objects.filter(cart=curr_cart, product=phone).exists():
            print("the current user is {}".format(curr_user_object.username))
            # curr_cart = Cart.objects.get(user=curr_user_object)
            cart_product = CartProduct(cart=curr_cart,product=phone,quantity=1)
            cart_product.save()
        else:
            print( )
    return render(request,'products/product_list.html',{'phone_matrix':phone_matrix})

def product_detail_view(request,product_id):
    global phone
    phone = models.Phone.objects.get(pk=product_id)
    
    MRP = phone.price
    if phone.brand == 'Apple':
        MRP = int(phone.price * 1.3)
    elif phone.brand == 'Samsung':
        MRP = int(phone.price * 1.2)
    else:
        MRP = int(phone.price * 1.1)

    return render(request,'products/product_details.html',{'phone':phone, 'MRP':MRP})

templates/products/product_details.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Product Details</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link waves-effect" href="{% url 'accounts:home' %}">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
      </ul>
      <ul class="navbar-nav nav-flex-icons">
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'accounts:account_page' %}">
            <!-- <span class="badge red z-depth-1 mr-1"> 1 </span> -->
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
          </a>
        </li>

        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'accounts:purchase_page' %}">
            <span class="clearfix d-none d-sm-inline-block"> Purchases </span>
          </a>
        </li>
      </ul>

    </div>

  </nav>
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">
      <div class="row wow fadeIn">
        <div class="col-md-6 mb-4">

          <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/14.jpg" class="img-fluid" alt=""> -->
          <img src="{{ phone.picture.url }}" width="400px">
        </div>
        <div class="col-md-6 mb-4">
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">Category 2</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-1">
                <del>{{MRP}}</del>
              </span>
              <span>₹{{phone.price}}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p><strong>{{phone.name}}</strong></p>
            <p>Color : {{phone.color}}</p>
            <p>Display : {{phone.display}}</p>
            <p>Storage : {{phone.storage}}GB</p>

            <form method="get" class="d-flex justify-content-left" action="{% url 'products:prodlist' %}">
              <!-- <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px"> -->
              <form method="get">
                <input class="btn btn-primary btn-md my-0 p" type="submit" value="Add to cart!" name="Add to cart!"/>
              </form>
            </form>

          </div>
        </div>
      </div>
      <hr>
      <div class="row d-flex justify-content-center wow fadeIn">
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Processor : {{phone.processor}}</p>
          <p>RAM : {{phone.ram}}GB</p>

        </div>
      </div>
      <div class="row wow fadeIn">
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
      </div>

    </div>
  </main>
  <hr class="my-4">
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript">
    new WOW().init();
  </script>
</body>

</html>

templates/products/product_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>List of Available Products</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }
  </style>
</head>

<body>
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{% url 'accounts:home' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        </ul>
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:account_page' %}">
              <!-- <span class="badge red z-depth-1 mr-1"> 1 </span> -->
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>

          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'accounts:purchase_page' %}">
              <span class="clearfix d-none d-sm-inline-block"> Purchases </span>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <main>
    <div class="container">
      <section class="text-center mb-4">
        <br><br><br><br>
{% block body_block %}
        <h1>Welcome! Here is the list of smartphones available for sale!</h1><br>
          {% for item in phone_matrix %}
            <div class="row wow fadeIn">
              {% for phone in item %}
              <div class="col-lg col-md-6 mb-4">
                <div class="card">
                  <div class="view overlay">
                    <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" alt=""> -->
                    <img src="{{ phone.picture.url }}" width="200px" style="width:100%">
                    <a>
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>

                  <div class="card-body text-center">
                    <a href="" class="grey-text">
                      <h5>{{phone.brand}}</h5>
                    </a>
                    <h5>
                      <strong>
                        <a href="{% url 'products:proddetail' product_id=phone.id %}" class="dark-grey-text">{{ phone.name }}
                          <span class="badge badge-pill danger-color">NEW</span>
                        </a>
                      </strong>
                    </h5>

                    <h4 class="font-weight-bold blue-text">
                      <strong>₹{{ phone.price }}</strong>
                    </h4>

                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
          {% endfor %}
{% endblock %}
      </section>
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>

          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>

          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
  </main>
  <hr class="my-4">
  <!--/.Footer-->

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();
  </script>
</body>

</html>