app1/urls.py
from django.urls import path
from app1 import views

urlpatterns = [
    path('',views.home, name='home'),
    path('signup/',views.signup, name='signup'),
    path('home/',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('about/',views.about, name='about')
]

eCom/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views as account_views
from merchant import views as merchant_views
from products import urls as produrls
from merchant import urls as mercurls
from django.conf.urls.static import static
from django.conf import settings
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mdb/',views.mdb_home_page_view,name="mdb_home_page"),
    path('',include('accounts.urls',namespace='accounts')),
    path('logout/',account_views.user_logout,name='user_logout'),
    path('products/',include(produrls,namespace='products')),
    path('merchant/',include(mercurls,namespace='merchant')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchant/urls.py
from django.urls import path
from merchant import views 
from accounts import views as account_views

#TEMPLATE URLS
app_name = 'merchant'

urlpatterns = [
    path('',views.merchant_login, name='merchant_login'),
    path('register',views.register_product, name='register_product'),
    path('merchant_login/',views.merchant_login, name='merchant_login'),
    path('logout/',views.merchant_logout,name='logout')
    # path('about/',account_views.about, name='about'),
]

merchant/models.py
from django.db import models

# Create your models here.
class Merchant(models.Model):
    merchant_name = models.CharField(max_length=200, unique=True)
    merchant_email = models.CharField(max_length=200)
    merchant_username = models.CharField(max_length=200)
    merchant_password = models.CharField(max_length=200)

    def __str__(self):
        return self.merchant_name

merchant/forms.py
from django import forms
from products.models import Phone

class ProductForm(forms.ModelForm):
    # Form fields
    name = forms.CharField(widget=forms.TextInput(attrs={'name':'product_name', 'type':'text', 'id':'product_name', 'class':'form-control', 'required':True, 'placeholder':"Enter Product Name"}))
    color = forms.CharField(widget=forms.TextInput(attrs={'name':'color', 'type':'text', 'id':'color', 'class':'form-control', 'required':True, 'placeholder':"Enter Color"}))
    display = forms.CharField(widget=forms.TextInput(attrs={'name':'display', 'type':'text', 'id':'display', 'class':'form-control', 'required':True, 'placeholder':"Enter Display"}))
    storage = forms.CharField(widget=forms.TextInput(attrs={'name':'storage', 'type':'text', 'id':'storage', 'class':'form-control', 'required':True, 'placeholder':"Enter Storage"}))
    camera = forms.CharField(widget=forms.TextInput(attrs={'name':'camera', 'type':'text', 'id':'camera', 'class':'form-control', 'required':True, 'placeholder':"Enter Camera"}))
    brand = forms.CharField(widget=forms.TextInput(attrs={'name':'brand', 'type':'text', 'id':'brand', 'class':'form-control', 'required':True, 'placeholder':"Enter Brand"}))
    processor = forms.CharField(widget=forms.TextInput(attrs={'name':'processor', 'type':'text', 'id':'processor', 'class':'form-control', 'required':True, 'placeholder':"Enter Processor"}))
    ram = forms.CharField(widget=forms.TextInput(attrs={'name':'ram', 'type':'text', 'id':'ram', 'class':'form-control', 'required':True, 'placeholder':"Enter RAM"}))
    price = forms.CharField(widget=forms.NumberInput(attrs={'name':'price', 'type':'number', 'id':'price', 'class':'form-control', 'required':True, 'placeholder':"Enter Price"}))
    # picture = forms.ImageField()
    class Meta():
        model = Phone
        fields = "__all__"

merchant/views.py
from django.shortcuts import render
from . import forms
from merchant.forms import ProductForm
from merchant.models import Merchant

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse

login_flag = False
curr_merchant = None

# Create your views here.
def register_product(request): 

    global login_flag
    global curr_merchant

    new_product_form = ProductForm

    registered = False

    if request.method == 'POST':
        new_product_form = ProductForm(request.POST, request.FILES)

        if new_product_form.is_valid(): 
            # current_product = new_product_form.save()
            new_product_form.save()
            registered = True
            # print("form valid but pic not found :(")

            # if 'picture' in request.FILES:
            #     print("found picture")
            #     current_product.picture = request.FILES['picture']

            # current_product.save()

        else:
            print("ERROR FORM INVALID")

    return render(request, 'merchant/register.html', {'form':new_product_form, 'login_flag':login_flag})

def merchant_logout(request):

    global curr_merchant
    global login_flag

    login_flag = False
    curr_merchant = None
    return HttpResponseRedirect(reverse('merchant:merchant_login'))

def merchant_login(request):

    global login_flag
    global curr_merchant

    if request.method == 'POST': 
        merchant_usrname = request.POST.get('merchant_username')
        merchant_passwrd = request.POST.get('merchant_password')

        if Merchant.objects.filter(merchant_username=merchant_usrname).exists() and Merchant.objects.get(merchant_username=merchant_usrname).merchant_password == merchant_passwrd:
            print("Merchant Logged in!")
            login_flag = True
            curr_merchant = merchant_usrname
            print("Current Merchant is " + curr_merchant)
            return HttpResponseRedirect(reverse('merchant:register_product'))

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and password: {}".format(merchant_usrname,merchant_passwrd))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request, 'merchant/register.html', {'login_flag':login_flag})

templates/merchant/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page</title>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'accounts:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if login_flag == True %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'merchant:logout' %}">Merchant Logout<span class="sr-only">(current)</span></a>
                    </li>

                {% endif %}
            </ul>
        </div>
    </nav>
    {% block inherit %}

    {% endblock %}
</body>
</html>

templates/merchant/register.html
<!DOCTYPE html>
{% extends "merchant/base.html" %}

{% block inherit %}
    <div class="container">
        <!-- {% if registered %}
            <div class="jumbotron">
                <h1>Thank you for Registering!</h1>
            </div>
        {% endif %} -->
        {% if login_flag == True %}
            <!-- {% if registered %}
                <div class="jumbotron">
                    <h1>Thank you for Registering!</h1>
                </div>
            {% endif %} -->
            <form enctype="multipart/form-data" method="POST">
                {% csrf_token %}

                <input type="hidden" name="csrf-token" value="CIwNZNlR4XbisJF39I8yWnWX9wX4WFoz" />

                <div class="container">
                    <div class="jumbotron">
                        <h1>Register your product</h1>
                    </div>
                </div>
                
                <div class="form-group">
                    {% csrf_token %}
                    <label for="product_name">Product Name:</label>
                    <!-- <input name="first_name" type="text" class="form-control" id="user_first_name" required> -->
                    {{ form.name }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="color">Color:</label>
                    <!-- <input name="last_name" type="text" class="form-control" id="user_last_name"> -->
                    {{ form.color }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="display">Display:</label>
                    <!-- <input name="delivery_address" type="text" class="form-control" id="user_address" required> -->
                    {{ form.display }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="storage">Storage:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.storage }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="camera">Camera:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.camera }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="brand">Brand:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.brand }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="processor">Processor:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.processor }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="ram">RAM:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.ram }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="picture">Picture:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.picture }}
                </div>

                <div class="form-group">
                    {% csrf_token %}
                    <label for="price">Price:</label>
                    <!-- <input name="phone_number" type="number" class="form-control" id="user_phone_number" required> -->
                    {{ form.price }}
                </div>

                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-block">Submit</button>
            </form>
        {% else %}
            <div class="container">
                <div class="jumbotron">
                    <h1>Please login to sell your product at our website!</h1>
                    {%csrf_token%}
                    <form method="post", action="{% url 'merchant:merchant_login' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="exampleInputUsername1">Username</label>
                            <input name="merchant_username" type="text" class="form-control" id="exampleInputUsername1" placeholder="Enter Username">
                            <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                        </div>
                        <div class="form-group">
                            <label for="exampleInputPassword1">Password</label>
                            <input name="merchant_password" type="password" class="form-control" id="exampleInputPassword1">
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}